parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_DRIVER): ''
    env(DATABASE_SERVER_VERSION): ''
    env(DATABASE_CHARSET): ''
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: '%env(resolve:DATABASE_DRIVER)%'
        server_version: '%env(resolve:DATABASE_SERVER_VERSION)%'
        charset: '%env(resolve:DATABASE_CHARSET)%'
        default_table_options:
            charset: '%env(resolve:DATABASE_CHARSET)%'
            collate: '%env(resolve:DATABASE_CHARSET)%_unicode_ci'

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
